// Generated by CoffeeScript 1.3.3
(function() {
  var applyStyle, keydownHandler, linkOpener, onKeyDown, onMouseOver, restoreStyle, styleBorderSelected;

  linkOpener = window.linkOpener = {
    isCtrlDown: false,
    elements: []
  };

  styleBorderSelected = '1px dashed orange';

  applyStyle = function(e) {
    e.dataset.styleBorderOld = e.style.border;
    return e.style.border = styleBorderSelected;
  };

  restoreStyle = function(e) {
    e.style.border = e.dataset.styleBorderOld;
    return e.dataset.styleBorderOld = null;
  };

  keydownHandler = function() {
    if (event.keyCode === 17) {
      linkOpener.isCtrlDown = true;
    }
    if (typeof window.onkeydownOld === 'function') {
      return window.onkeydownOld();
    }
  };

  onKeyDown = function() {
    var hashedListLinks, i, j;
    if (event.keyCode === 17) {
      linkOpener.isCtrlDown = false;
      hashedListLinks = {};
      i = 0;
      while (i < linkOpener.elements.length) {
        restoreStyle(linkOpener.elements[i]);
        hashedListLinks[linkOpener.elements[i].href] = true;
        i++;
      }
      linkOpener.elements = [];
      for (j in hashedListLinks) {
        open(j);
      }
    }
    if (typeof window.onkeyupOld === 'function') {
      return window.onkeyupOld();
    }
  };

  onMouseOver = function(e) {
    var index;
    if (e.shiftKey) {
      if (this.attributes.styleBorderOld || this.attributes.styleBorderOld === '') {
        restoreStyle(this);
        index = linkOpener.elements.indexOf(this);
        if (index >= 0) {
          linkOpener.elements.splice(index, 1);
        }
      } else {
        linkOpener.elements.push(this);
        applyStyle(this);
      }
    }
    if (typeof this.onmouseoverOld === 'function') {
      return this.onmouseoverOld();
    }
  };

  window.addEventHandler('keydown', onKeyDown);

  window.addEventHandler('mouseover', onMouseOver);

}).call(this);
